# Generated by Django 5.2.7 on 2025-11-08 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='health_package',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
