# Generated by Django 5.2.7 on 2025-11-11 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0003_health_package_created_by_alter_health_package_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='health_package',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10),
        ),
    ]
