# Generated by Django 5.2.7 on 2025-11-27 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
