# Generated by Django 5.2.7 on 2025-11-19 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='schedule',
        ),
        migrations.AddField(
            model_name='appointment',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='slot',
            field=models.CharField(blank=True, choices=[('M', 'Morning slot'), ('E', 'Evening slot')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='patient_email',
            field=models.EmailField(max_length=254),
        ),
    ]
