# Generated by Django 5.2.7 on 2025-11-27 06:39

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0002_remove_appointment_schedule_appointment_date_and_more'),
        ('doctors', '0014_remove_doctor_chamber_time_alter_chambertime_drcode_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='date',
            new_name='Dob',
        ),
        migrations.RenameField(
            model_name='appointment',
            old_name='patient_phone',
            new_name='MobileNo',
        ),
        migrations.RenameField(
            model_name='appointment',
            old_name='patient_name',
            new_name='PatientName',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='department_name',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='doctor_name',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='patient_email',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='slot',
        ),
        migrations.AddField(
            model_name='appointment',
            name='AgeDay',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='AgeMonth',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='AgeYear',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='DrCode',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments_by_code', to='doctors.doctor'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='DrName',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments_by_name', to='doctors.doctor'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='PatientEmail',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='Sex',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='VisitAmount',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='VisitDate',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='appointment',
            name='VisitType',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='appointment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
