# Generated by Django 5.2.7 on 2025-11-17 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_appointment', models.PositiveIntegerField(default=0)),
                ('specialists', models.PositiveIntegerField(default=0)),
                ('happy_patients', models.PositiveIntegerField(default=0)),
                ('winning_awards', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RenameField(
            model_name='hero',
            old_name='image',
            new_name='mobile_image',
        ),
        migrations.AddField(
            model_name='hero',
            name='pc_image',
            field=models.ImageField(blank=True, null=True, upload_to='media/hero/'),
        ),
        migrations.AddField(
            model_name='hero',
            name='tab_image',
            field=models.ImageField(blank=True, null=True, upload_to='media/hero/'),
        ),
    ]
