# Generated by Django 5.2.7 on 2025-11-17 09:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_badge_rename_image_hero_mobile_image_hero_pc_image_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='banner',
            old_name='image',
            new_name='mobile_image',
        ),
        migrations.AddField(
            model_name='banner',
            name='pc_image',
            field=models.ImageField(blank=True, null=True, upload_to='media/banner/'),
        ),
        migrations.AddField(
            model_name='banner',
            name='tab_image',
            field=models.ImageField(blank=True, null=True, upload_to='media/banner/'),
        ),
        migrations.CreateModel(
            name='Facilities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('points', models.TextField(blank=True, help_text='Write each point separated by a comma', null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='media/facilities')),
                ('open_hour', models.TextField(blank=True, help_text='Write hours separated by comma, e.g., Saturday 6:00 am - 10:00 pm, Sunday 6:00 am - 10:00 pm', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
