# Generated by Django 5.2.7 on 2025-11-19 07:16

import home.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_herobadge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='herobadge',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='media/HeroBadge', validators=[home.models.validate_image_file]),
        ),
    ]
