# Generated by Django 5.2.7 on 2025-11-24 05:44

import home.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_herobadge_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about_us',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/about/'),
        ),
        migrations.AlterField(
            model_name='herobadge',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='media/HeroBadge/', validators=[home.models.validate_image_file]),
        ),
    ]
