# Generated by Django 5.2.7 on 2025-11-24 08:17

import home.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_about_us_image_alter_herobadge_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about_us',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='about/'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='mobile_image',
            field=models.ImageField(blank=True, null=True, upload_to='banner/'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='pc_image',
            field=models.ImageField(blank=True, null=True, upload_to='banner/'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='tab_image',
            field=models.ImageField(blank=True, null=True, upload_to='banner/'),
        ),
        migrations.AlterField(
            model_name='facilities',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='facilities'),
        ),
        migrations.AlterField(
            model_name='hero',
            name='mobile_image',
            field=models.ImageField(blank=True, null=True, upload_to='hero/'),
        ),
        migrations.AlterField(
            model_name='hero',
            name='pc_image',
            field=models.ImageField(blank=True, null=True, upload_to='hero/'),
        ),
        migrations.AlterField(
            model_name='hero',
            name='tab_image',
            field=models.ImageField(blank=True, null=True, upload_to='hero/'),
        ),
        migrations.AlterField(
            model_name='herobadge',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='HeroBadge/', validators=[home.models.validate_image_file]),
        ),
    ]
