# Generated by Django 5.2.7 on 2025-11-25 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_about_us_image_alter_banner_mobile_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='herobadge',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
