# Generated by Django 5.2.7 on 2025-11-25 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_alter_herobadge_title'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contact',
            new_name='ContactHome',
        ),
    ]
