# Generated by Django 5.2.7 on 2025-11-24 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0002_alter_doctor_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='department/'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='doctor/'),
        ),
    ]
