# Generated by Django 5.2.7 on 2025-11-05 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0003_schedule_doctor_schedule'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='day_name',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='start_time',
        ),
        migrations.AddField(
            model_name='schedule',
            name='day',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='schedule',
            name='time',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
    ]
