# Generated by Django 5.2.7 on 2025-11-25 11:31

import home.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0004_schedule_created_at_schedule_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='department/', validators=[home.models.validate_image_file]),
        ),
    ]
