# Generated by Django 5.2.7 on 2025-11-05 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0004_remove_schedule_day_name_remove_schedule_end_time_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepartmentGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(blank=True, max_length=250, null=True)),
                ('departments', models.ManyToManyField(blank=True, related_name='groups', to='doctors.department')),
            ],
        ),
    ]
