# Generated by Django 5.2.7 on 2025-11-26 04:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0005_alter_department_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BestDoctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor_department', models.CharField(blank=True, max_length=255, null=True)),
                ('doctor_about', models.TextField(blank=True, null=True)),
                ('doctor_skills', models.TextField(blank=True, help_text='Write skills separated by comma', null=True)),
                ('doctor_experiance', models.PositiveIntegerField(blank=True, null=True)),
                ('award_title', models.CharField(blank=True, max_length=255, null=True)),
                ('award_description', models.TextField(blank=True, null=True)),
                ('award_image', models.FileField(blank=True, null=True, upload_to='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('doctor_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bestdoctor_image_set', to='doctors.doctor')),
                ('doctor_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bestdoctor_name_set', to='doctors.doctor')),
            ],
        ),
    ]
