# Generated by Django 5.2.7 on 2025-11-11 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0006_department_created_by_departmentgroup_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='Media/doctor/'),
        ),
    ]
