# Generated by Django 5.2.7 on 2025-11-26 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0006_bestdoctor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bestdoctor',
            old_name='doctor_department',
            new_name='best_in_field',
        ),
    ]
