# Generated by Django 5.2.7 on 2025-11-26 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0007_rename_doctor_department_bestdoctor_best_in_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bestdoctor',
            name='doctor_image',
            field=models.FileField(blank=True, null=True, upload_to='best_doctors/'),
        ),
    ]
