# Generated by Django 5.2.7 on 2025-11-26 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0008_alter_bestdoctor_doctor_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='service_image',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
