# Generated by Django 5.2.7 on 2025-11-26 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0009_service_service_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bestdoctor',
            name='award_image',
            field=models.FileField(blank=True, null=True, upload_to='best_doctors_award/'),
        ),
    ]
