# Generated by Django 5.2.7 on 2025-11-27 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0010_alter_bestdoctor_award_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='name',
            new_name='drName',
        ),
        migrations.AddField(
            model_name='doctor',
            name='drCode',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
