# Generated by Django 5.2.7 on 2025-11-27 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0011_rename_name_doctor_drname_doctor_drcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
