# Generated by Django 5.2.7 on 2025-11-27 04:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0012_alter_department_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='schedule',
        ),
        migrations.CreateModel(
            name='ChamberTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drCode', models.CharField(max_length=100)),
                ('dayName', models.CharField(max_length=100)),
                ('visitType', models.CharField(max_length=100)),
                ('startTime', models.CharField(max_length=100)),
                ('finishTime', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='doctor',
            name='chamber_time',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='doctors', to='doctors.chambertime'),
        ),
        migrations.DeleteModel(
            name='Schedule',
        ),
    ]
