# Generated by Django 5.2.7 on 2025-11-27 04:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0013_remove_doctor_schedule_chambertime_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='chamber_time',
        ),
        migrations.AlterField(
            model_name='chambertime',
            name='drCode',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='doctors.doctor'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
    ]
